# Generated by Django 4.1.7 on 2023-10-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('bankid', models.AutoField(primary_key=True, serialize=False)),
                ('bankname', models.CharField(default='', max_length=20)),
                ('Accountnumber', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
