# Generated by Django 4.1.7 on 2023-10-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='bankid',
            new_name='id',
        ),
    ]
